main: com.mccritz.kmain.kMain
name: kMain
version: 1.0
description: Advanced all in one plugin which containts utilities related to the Teams gamemode that utilizes MongoDB.
author: Calvin
authors: [The McCritz Development Team]
depends: [kBasic]